import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./jobListing.css"
import "./jbInfoSect.css"
import "./lancerPage.css"
import "./lancerDtls.css"
import "./searchBar.css"
import "./messagesPg.css"
import "./notifications.css"
import "./apply.css"
import "./lancerHomePage.css"
import "./lancrContact.css"
import "./dedicatedServiceLancr.css"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
